//
//  ForeCastHomeRouter.swift
//  AppWeather
//
//  Created by Jirawat on 28/10/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ForeCastHomeRoutingLogic {
}

protocol ForeCastHomeDataPassing {
    var dataStore: ForeCastHomeDataStore? { get }
}

class ForeCastHomeRouter: NSObject, ForeCastHomeRoutingLogic, ForeCastHomeDataPassing {
    weak var viewController: ForeCastHomeViewController?
    var dataStore: ForeCastHomeDataStore?
}
