//
//  ForeCastHomeWorker.swift
//  AppWeather
//
//  Created by Jirawat on 28/10/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol ForeCastHomeWorkable {
    func getForeCast(city: String) -> Single<GetForeCastHomeResponse>
}

final class ForeCastHomeWorker: ForeCastHomeWorkable {
    private let getForeCastUsecase: GetForeCastHomeUsecase!
    init(getForeCastUsecase: GetForeCastHomeUsecase? = GetForeCastHomeUsecaseImpl()) {
        self.getForeCastUsecase = getForeCastUsecase
    }

    func getForeCast(city: String) -> Single<GetForeCastHomeResponse> {
        return getForeCastUsecase.execute(city: city)
    }
}
