//
//  ForeCastHomeRouter.swift
//  AppWeather
//
//  Created by Jirawat on 28/10/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ForeCastHomeRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ForeCastHomeDataPassing {
    var dataStore: ForeCastHomeDataStore? { get }
}

class ForeCastHomeRouter: NSObject, ForeCastHomeRoutingLogic, ForeCastHomeDataPassing {
    weak var viewController: ForeCastHomeViewController?
    var dataStore: ForeCastHomeDataStore?

// MARK: Routing (navigating to other screens)

//func routeToSomewhere(segue: UIStoryboardSegue?) {
//    if let segue = segue {
//        let destinationVC = segue.destination as! SomewhereViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//    } else {
//        let storyboard = UIStoryboard(name: "Main", bundle: nil)
//        let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        navigateToSomewhere(source: viewController!, destination: destinationVC)
//    }
//}

// MARK: Navigation to other screen

//func navigateToSomewhere(source: ForeCastHomeViewController, destination: SomewhereViewController) {
//    source.show(destination, sender: nil)
//}

// MARK: Passing data to other screen

//    func passDataToSomewhere(source: ForeCastHomeDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
