//
//  ForeCastHomePresenter.swift
//  AppWeather
//
//  Created by Jirawat on 28/10/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForeCastHomePresentationLogic {
    func presentSomething(response: ForeCastHome.Something.Response)
}

class ForeCastHomePresenter: ForeCastHomePresentationLogic {
    weak var viewController: ForeCastHomeDisplayLogic?

    // MARK: Parse and calc respnse from ForeCastHomeInteractor and send simple view model to ForeCastHomeViewController to be displayed

    func presentSomething(response: ForeCastHome.Something.Response) {
        let viewModel = ForeCastHome.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: ForeCastHome.SomethingElse.Response) {
//        let viewModel = ForeCastHome.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
