//
//  ForeCastHomePresenter.swift
//  AppWeather
//
//  Created by Jirawat on 28/10/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForeCastHomePresentationLogic {
    func presentGreeting(response: ForeCastHome.Show.Response)
    
    func presentTableReloadData()
}

class ForeCastHomePresenter: ForeCastHomePresentationLogic {
    weak var viewController: ForeCastHomeDisplayLogic?

    func presentGreeting(response: ForeCastHome.Show.Response) {
        let city = response.name
        let viewModel = ForeCastHome.Show.ViewModel(city: city)
        viewController?.displayGreeting(viewModel: viewModel)
    }
    
    func presentTableReloadData() {
        viewController?.displayTableReloadData()
    }

}
