//
//  WeatherHomePresenter.swift
//  AppWeather
//
//  Created by Jirawat on 27/10/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherHomePresentationLogic {
    func presentTableReloadData()
    func presentWeatherDetail()
}

final class WeatherHomePresenter: WeatherHomePresentationLogic {
    weak var viewController: WeatherHomeDisplayLogic?

    func presentTableReloadData() {
        viewController?.displayTableReloadData()
    }

    func presentWeatherDetail() {
        viewController?.displayWeatherDetail()
    }
}
