//
//  WeatherHomeWorker.swift
//  AppWeather
//
//  Created by Jirawat on 27/10/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import RxSwift
import UIKit

protocol WeatherHomeWorkable {
    func getHomeWeather(city: String) -> Single<GetWeatherHomeResponse>
}

final class WeatherHomeWorker: WeatherHomeWorkable {
    private let getHomeWeatherUsecase: GetHomeWeatherUsecase!
    init(getHomeWeatherUsecase: GetHomeWeatherUsecase? = GetHomeWeatherUsecaseImpl()) {
        self.getHomeWeatherUsecase = getHomeWeatherUsecase
    }

    func getHomeWeather(city: String) -> Single<GetWeatherHomeResponse> {
        return getHomeWeatherUsecase.execute(city: city)
    }
}
