//
//  WeatherHomeViewController.swift
//  AppWeather
//
//  Created by Jirawat on 27/10/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherHomeDisplayLogic: class {
    func displayTableReloadData()
    func displayWeatherDetail()
}

final class WeatherHomeViewController: UIViewController, WeatherHomeDisplayLogic {
    @IBOutlet private var tableView: UITableView!
    @IBOutlet var searchBar: UISearchBar!
    var interactor: WeatherHomeBusinessLogic?

    var router: (NSObjectProtocol & WeatherHomeRoutingLogic & WeatherHomeDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = WeatherHomeInteractor()
        let presenter = WeatherHomePresenter()
        let router = WeatherHomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        setView()
        interactor?.fetch()
    }

    // Private
    private func setView() {
        title = "Weather"

    }
}

// MARK: WeatherHomeDisplayLogic

extension WeatherHomeViewController {
    func displayTableReloadData() {
//        tableView.reloadData()
    }

    func displayWeatherDetail() {
    }
}
