//
//  WeatherHomeRouter.swift
//  AppWeather
//
//  Created by Jirawat on 27/10/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WeatherHomeRoutingLogic {
    func routeToWeatherDetail()
}

protocol WeatherHomeDataPassing {
    var dataStore: WeatherHomeDataStore? { get }
}

final class WeatherHomeRouter: NSObject, WeatherHomeRoutingLogic, WeatherHomeDataPassing {
    weak var viewController: WeatherHomeViewController?
    var dataStore: WeatherHomeDataStore?

    func routeToWeatherDetail() {
    }
}
