//
//  WeatherHomeInteractor.swift
//  AppWeather
//
//  Created by Jirawat on 27/10/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherHomeBusinessLogic {
    func doSomething(request: WeatherHome.Something.Request)
//    func doSomethingElse(request: WeatherHome.SomethingElse.Request)
}

protocol WeatherHomeDataStore {
    //var name: String { get set }
}

class WeatherHomeInteractor: WeatherHomeBusinessLogic, WeatherHomeDataStore {
    var presenter: WeatherHomePresentationLogic?
    var worker: WeatherHomeWorker?
    //var name: String = ""

    // MARK: Do something (and send response to WeatherHomePresenter)

    func doSomething(request: WeatherHome.Something.Request) {
        worker = WeatherHomeWorker()
        worker?.doSomeWork()

        let response = WeatherHome.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: WeatherHome.SomethingElse.Request) {
//        worker = WeatherHomeWorker()
//        worker?.doSomeOtherWork()
//
//        let response = WeatherHome.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
